name: stockpathshala_beta
description: Stock Pathshala is the first app that you MUST install if you are even thinking of investing in the Stock Market.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 2.1.2+275
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  win32: any
#  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.2

#  ordered_set: ^6.1.1
  get: ^4.6.6
  account_picker: ^2.2.0
  phone_number_hint: ^0.0.5
  flutter_svg: ^2.0.17
#  easy_stepper: ^0.8.3
#  palette_generator: ^0.3.3+5
  get_storage: ^2.0.3
  pulsator: ^1.0.0+2
  shared_preferences: ^2.2.3
  responsive_framework: ^0.2.0
  pin_code_text_field: ^1.8.0
  fluttertoast: ^8.0.9
#  cached_network_image: ^3.3.0
  image_picker: ^0.8.6
  dio: ^4.0.6
  dio_logging_interceptor: ^1.0.1
  get_it: ^7.2.0
#  url_launcher: ^6.1.6
  permission_handler: ^12.0.0+1
  shimmer: ^3.0.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.2.5
  firebase_analytics: ^10.7.4
  firebase_dynamic_links: ^5.4.8
  flutter_local_notifications: ^18.0.1
  wakelock_plus: ^1.3.2
#  division: 0.9.0
  firebase_crashlytics: ^3.4.8
  dotted_border: ^2.0.0+3
  percent_indicator: ^4.2.2
  flash: ^3.1.1
  fl_chart: ^0.66.1
  youtube_player_iframe: ^4.0.4
  #html
  flutter_html: ^3.0.0-alpha.5
#  flutter_html_table: ^3.0.0-alpha.3
#  flutter_layout_grid: ^1.0.1
  flutter_widget_from_html: ^0.10.0
  easy_debounce: any
  card_swiper: ^2.0.4
  share_plus:
  carousel_slider: ^5.0.0
  curl_logger_dio_interceptor: ^0.0.3
  glowy_borders: ^1.0.2
  razorpay_flutter: ^1.3.4
  in_app_purchase: ^3.2.0
  better_player:
    git:
      url: https://github.com/AnonymHK/betterplayer.git
      ref: master
# path_provider: any
  youtube_explode_dart: any
  readmore: ^2.1.0
#  just_audio: ^0.9.32
  audio_service: ^0.18.7
  #  audio_session: ^0.1.23
  device_info_plus: ^11.2.0
  file_manager: ^1.0.1
  path: ^1.8.2
  native_exif: ^0.4.1
  floor: ^1.4.1
  video_player: ^2.10.0
  flutter_isolate: ^2.0.4
  youtube_player_flutter: any
 # visibility_detector:
  sms_autofill: ^2.4.0
  http: any
  lottie: ^2.3.2
#  package_info_plus: ^8.1.2
  screen_protector: ^1.4.2+1
#  stacked_page_view: ^1.1.2
  open_file: ^3.3.2
  overlay_tooltip: ^0.2.3
  in_app_update: ^4.2.2
  in_app_review: ^2.0.10
  confetti: ^0.8.0
  flutter_avif: ^2.4.1
  mobile_number: ^3.0.0
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.0.9
  intl: ^0.18.1
  smooth_page_indicator: ^1.2.1
  font_awesome_flutter: ^10.9.1
  sensors_plus: ^6.1.2
  web_socket_channel: ^2.4.0
  socket_io_client: ^3.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
#  floor_generator: ^1.4.1
#  analyzer: ^5.0.0
#  build_runner: ^2.2.1
flutter:
  uses-material-design: true
  assets:
    - assets/app/
    - assets/
    - assets/images/
    - assets/svg/
    - assets/images/buy_bttn.png
    - assets/images/view_images/
    - assets/images/view_images/container_images/
    - assets/images/icons/
    - assets/images/banners/
    - assets/images/app_logo/
    - assets/images/placeholder_and_error/
  fonts:
    - family: "Poppins"
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
